create table if not exists public.user_study_responses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  timestamp_utc text,
  participant_id text,
  bundle_id text,
  trial_id text,
  task_label text,
  question_id text,
  question_text text,
  option_label text,
  method text,
  display_order integer,
  rating integer,
  rating_label text
);

create index if not exists user_study_responses_participant_idx
  on public.user_study_responses (participant_id);

create index if not exists user_study_responses_trial_idx
  on public.user_study_responses (trial_id);

create index if not exists user_study_responses_question_idx
  on public.user_study_responses (question_id);
