create table if not exists public.user_study_responses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  timestamp_utc text,
  participant_id text,
  assigned_id text,
  bundle_id text,
  trial_id text,
  task_label text,
  question_id text,
  question_text text,
  option_label text,
  method text,
  display_order integer,
  rating integer,
  rating_label text
);

create index if not exists user_study_responses_participant_idx
  on public.user_study_responses (participant_id);

create index if not exists user_study_responses_trial_idx
  on public.user_study_responses (trial_id);

create index if not exists user_study_responses_question_idx
  on public.user_study_responses (question_id);

-- New isolated-submission storage used when [supabase].url is a PostgreSQL
-- connection string. The app creates one response table per participant
-- submission and records the table name here.
create table if not exists public.user_study_submissions (
  submission_id text primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  bundle_id text,
  assigned_id text,
  prolific_pid text,
  prolific_pid_hash text,
  study_id text,
  session_id text,
  response_table_name text,
  status text,
  saved_scene_count integer default 0,
  exit_status text
);

create index if not exists user_study_submissions_bundle_idx
  on public.user_study_submissions (bundle_id);

create index if not exists user_study_submissions_status_idx
  on public.user_study_submissions (status);

-- Template for the dynamically-created per-submission response tables.
-- Each real table is named like:
-- public.user_study_responses_p001_0123abcd4567
create table if not exists public.user_study_responses_template (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  submission_id text,
  timestamp_utc text,
  participant_id text,
  assigned_id text,
  prolific_pid text,
  prolific_pid_hash text,
  bundle_id text,
  study_id text,
  session_id text,
  scene_slot integer,
  trial_id text,
  task_label text,
  question_id text,
  question_text text,
  option_label text,
  method text,
  display_order integer,
  rating integer,
  rating_label text
);
